name: flutter_ecommerce
description: A new Flutter application.
publish_to: "none" 
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  cloud_firestore: ^2.3.0
  flutter_screenutil: ^5.0.0+2
  fluttertoast: ^8.0.7
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  uuid: ^3.0.4
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/images/
  uses-material-design: true